<p>
    Your current assignment is with <b><?php echo $this->hospital->name; ?></b>,
    started on <?php echo $this->assignment->start; ?>
</p>
<p>
    You can end your current assignment and start a new one:
</p>

<form action="/index/new_assignment" method="POST">
    <table class="table">
        <th>
            <td>Hospital:</td>
            <td>
                <select name="hospital_id">
                    <?php foreach ($this->hospitals as $hospital) { ?>
                        <option value="<?php echo $hospital->id; ?>"><?php echo $hospital->name; ?></option>
                    <?php } ?>
                </select>
            </td>
        </th>
    </table>

    <table class="table table-striped">
        <thead>
        <tr>
        </tr>
        <tr>
            <th>Build task list:</th>
            <th>
            </th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($this->tasks as $task) { ?>
            <tr>
                <td><?php echo $task->description; ?></td>
                <td>
                    <div class="pull-right">
                        <input type="checkbox" name="task_id[]" value="<?php echo $task->id; ?>">
                    </div>
                </td>
            </tr>
        <?php } ?>
            <tr><td colspan="2">
                <input type="submit" class="btn btn-success" value="Start assignment">
            </td></tr>
        </tbody>
    </table>
</form>
<?php
