<h3>Not implemented yet, content is static</h3>

<h3>Tips and Tricks</h3>
<table class="table table-striped">
    <thead>
    <tr>
        <th>Title</th>
        <th>Date</th>
        <th>Comments</th>

    </tr>
    </thead>
    <tbody>
    <tr>
        <td><a href="tip01.html">Good medical student teaching in Main lecture theatre wednesday lunchtimes!</a></td>
        <td>25/05/2013 14:54</td>
        <td>6</td>
    </tr>
    <tr>
        <td><a href="tip02.html">Need to practice I/M injections</a></td>
        <td>24/05/2013 09:23</td>
        <td>4</td>
    </tr>
    <tr>
        <td><a href="tip03.html">Good consultant teaching round on Thursday mornings.</a></td>
        <td>13/04/2013 12:40</td>
        <td>4</td>
    </tr>
    </tbody>
</table>
